name: Assertion Based Evals

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  evals-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r customer_support_ai/requirements.txt
    
    - name: Run classification assertion tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python customer_support_ai/evals/test_classification_assertions.py